sudo: required
services:
  - docker

before_install:
  - docker build -t jih1092574/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true jih1092574/docker-react npm run test

language: generic 